version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install DaggerWrapper
          command: pip install git+https://github.com/levlaz/dagger-wrapper

      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true

      # Run Dagger
      - run: python main.py

